#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#
    set(recastLibraries DebugUtils;Detour;DetourCrowd;DetourTileCache;Recast)
    foreach(recastLibrary ${recastLibraries})
        add_library(RecastNavigation::${recastLibrary} STATIC IMPORTED GLOBAL)

        set_target_properties(RecastNavigation::${recastLibrary} 
            PROPERTIES 
                IMPORTED_LOCATION 
                    "${LY_ROOT_FOLDER}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}${recastLibrary}${CMAKE_STATIC_LIBRARY_SUFFIX}")

        target_compile_definitions(RecastNavigation::${recastLibrary} 
            INTERFACE 
                DT_POLYREF64)

        ly_target_include_system_directories(TARGET RecastNavigation::${recastLibrary} 
            INTERFACE 
                "${LY_ROOT_FOLDER}/include/recastnavigation")
    endforeach()

# Generated by O3DE

ly_add_target(
    NAME RecastNavigation.API IMPORTED HEADERONLY
    NAMESPACE Gem
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            Include
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            RecastNavigation::Detour
            RecastNavigation::Recast
    RUNTIME_DEPENDENCIES

    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Windows/Default/RecastNavigation.API_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME RecastNavigation.Private.Object IMPORTED STATIC
    NAMESPACE Gem
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            AZ::AzFramework
            RecastNavigation::DebugUtils
            RecastNavigation::Detour
            RecastNavigation::Recast
            Gem::LmbrCentral.Static
            Gem::DebugDraw.Static
    RUNTIME_DEPENDENCIES

    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Windows/Default/RecastNavigation.Private.Object_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME RecastNavigation IMPORTED GEM_MODULE
    NAMESPACE Gem
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            Include
    BUILD_DEPENDENCIES
        INTERFACE
            Gem::RecastNavigation.API
    RUNTIME_DEPENDENCIES
        Gem::RecastNavigation.Private.Object
    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Windows/Default/RecastNavigation_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME RecastNavigation.Editor.API IMPORTED HEADERONLY
    NAMESPACE Gem
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            Include
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzToolsFramework
    RUNTIME_DEPENDENCIES

    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Windows/Default/RecastNavigation.Editor.API_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME RecastNavigation.Editor.Private.Object IMPORTED STATIC
    NAMESPACE Gem
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzToolsFramework
            Gem::RecastNavigation.Private.Object
            Gem::LmbrCentral.Static
            Gem::DebugDraw.Static
    RUNTIME_DEPENDENCIES

    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Windows/Default/RecastNavigation.Editor.Private.Object_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME RecastNavigation.Editor IMPORTED GEM_MODULE
    NAMESPACE Gem
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            Include
    BUILD_DEPENDENCIES
        INTERFACE
            Gem::RecastNavigation.Editor.API
    RUNTIME_DEPENDENCIES
        Gem::RecastNavigation.Editor.Private.Object
    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Windows/Default/RecastNavigation.Editor_${config}.cmake" OPTIONAL)
endforeach()

if(NOT TARGET RecastNavigation.Clients)
   ly_create_alias( NAME RecastNavigation.Clients NAMESPACE Gem TARGETS Gem::RecastNavigation)
endif()
if(NOT TARGET RecastNavigation.Servers)
   ly_create_alias( NAME RecastNavigation.Servers NAMESPACE Gem TARGETS Gem::RecastNavigation)
endif()
if(NOT TARGET RecastNavigation.Clients.API)
   ly_create_alias( NAME RecastNavigation.Clients.API NAMESPACE Gem TARGETS Gem::RecastNavigation.API)
endif()
if(NOT TARGET RecastNavigation.Servers.API)
   ly_create_alias( NAME RecastNavigation.Servers.API NAMESPACE Gem TARGETS Gem::RecastNavigation.API)
endif()
if(NOT TARGET RecastNavigation.Tools)
   ly_create_alias( NAME RecastNavigation.Tools NAMESPACE Gem TARGETS Gem::RecastNavigation.Editor)
endif()
if(NOT TARGET RecastNavigation.Builders)
   ly_create_alias( NAME RecastNavigation.Builders NAMESPACE Gem TARGETS Gem::RecastNavigation.Editor)
endif()
if(NOT TARGET RecastNavigation.Tools.API)
   ly_create_alias( NAME RecastNavigation.Tools.API NAMESPACE Gem TARGETS Gem::RecastNavigation.Editor.API)
endif()
if(NOT TARGET RecastNavigation.Builders.API)
   ly_create_alias( NAME RecastNavigation.Builders.API NAMESPACE Gem TARGETS Gem::RecastNavigation.Editor.API)
endif()
