# Generated by O3DE install

set_property(TARGET RecastNavigation.Editor
    APPEND_STRING PROPERTY IMPORTED_LOCATION
        $<$<CONFIG:profile>:${LY_ROOT_FOLDER}/bin/Windows/profile/Default/./RecastNavigation.Editor.dll>
)
set_property(TARGET RecastNavigation.Editor
    PROPERTY IMPORTED_LOCATION_PROFILE
        ${LY_ROOT_FOLDER}/bin/Windows/profile/Default/./RecastNavigation.Editor.dll
)
